# Generated by Django 3.2.4 on 2021-06-26 08:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='category',
            fields=[
                ('categoryid', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='questions',
            fields=[
                ('quesid', models.IntegerField(primary_key=True, serialize=False)),
                ('questext', models.CharField(max_length=100)),
                ('answer', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='quizRespoonse',
            fields=[
                ('responseid', models.IntegerField(primary_key=True, serialize=False)),
                ('givenanswer', models.CharField(max_length=100)),
                ('status', models.BooleanField(default=False)),
                ('ques', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.questions')),
            ],
        ),
        migrations.CreateModel(
            name='quiz',
            fields=[
                ('quizid', models.IntegerField(primary_key=True, serialize=False)),
                ('quizname', models.CharField(max_length=100)),
                ('createdby', models.CharField(max_length=100)),
                ('quizdate', models.DateField()),
                ('totalquestion', models.IntegerField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.category')),
            ],
        ),
        migrations.AddField(
            model_name='questions',
            name='quiz',
            field=models.ManyToManyField(to='quiz.quiz'),
        ),
        migrations.CreateModel(
            name='possibleanswers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer1', models.CharField(max_length=100)),
                ('answer2', models.CharField(max_length=100)),
                ('answer3', models.CharField(max_length=100)),
                ('answer4', models.CharField(max_length=100)),
                ('ques', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.questions')),
            ],
        ),
    ]
